# Generated by Django 5.0.13 on 2025-04-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "useruid",
                    models.AutoField(
                        db_column="UserUID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "userid",
                    models.CharField(db_column="UserID", max_length=30, unique=True),
                ),
                ("pw", models.CharField(db_column="Pw", max_length=50)),
                (
                    "enpassword",
                    models.CharField(
                        blank=True, db_column="Enpassword", max_length=255, null=True
                    ),
                ),
                (
                    "joindate",
                    models.DateTimeField(
                        auto_now_add=True, db_column="JoinDate", null=True
                    ),
                ),
                ("admin", models.BooleanField(db_column="Admin", default=False)),
                ("adminlevel", models.IntegerField(db_column="AdminLevel", default=0)),
                ("status", models.IntegerField(db_column="Status", default=0)),
                ("email", models.EmailField(db_column="Email", max_length=50)),
                ("usertype", models.IntegerField(db_column="UserType", default=0)),
                (
                    "user_ip",
                    models.CharField(
                        blank=True, db_column="UserIp", max_length=45, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Users_Master",
            },
        ),
    ]
