# Generated by Django 5.0.13 on 2025-04-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asgard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsupdate",
            options={
                "managed": False,
                "ordering": ["-published_date"],
                "verbose_name": "Noticia",
                "verbose_name_plural": "Noticias",
            },
        ),
    ]
